### PR TITLE
update links to documentation in tutorial to latest version

### PR DESCRIPTION
**Pull request by bakotaco**
update links to documentation in tutorial from 1.0-RC3 to 1.0

### CODE REVIEW

**Comment by ktoso** [comment]
Great catch, thanks!

**Comment by ktoso** [comment]
Before we merge can I ask you to sign our contributor agreement (CLA)?

It's very simple, you just need to click through this form (and confirm with your github account):
http://www.typesafe.com/contribute/cla

Thanks!

**Comment by bakotaco** [comment]
@ktoso signed the CLA. Cheers

**Comment by ktoso** [comment]
Great, thanks!

**Pull request merged**
